# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.wallet.bike/
title: 骑车挖矿
email: jinjiulian@yahoo.com
author: cr4fun
description: > # "Write an awesome description for your new site here. 
  骑车挖矿，是全球首个基于DAG区块链的共享单车，通过骑车可以获得Token激励。
copyright: 'Copyright &copy; 2018 www.wallet.bike All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/walletbike
